projects:
    acme/stories:
        references: [shared, app1, app2]
        environments: [types, web, mocks, tests, stories]
    acme/app1:
        references: [shared]
        environments: [types, web, mocks, tests, stories]
    acme/app2:
        references: [shared]
        environments: [types, web, mocks, tests, stories]
    acme/shared:
        environments: [types, web, mocks, tests, stories]

environments:
    types:
        include: ['src/**/*.types.{ts,tsx,mts}']
    web:
        extends: [web]
        references: [types]
        include: ['src/**/*.{ts,tsx,mts}']
        exclude: ['src/**/*.{types,mocks,tests,stories}.{ts,tsx,mts}']
    mocks:
        extends: [base]
        references: [types, web]
        include: ['src/**/*.mocks.{ts,tsx,mts}']
        types: ['vitest/global']
    tests:
        extends: [web]
        references: [types, web, mocks]
        include: ['src/**/*.tests.{ts,tsx,mts}']
        types: ['vitest/global']
    stories:
        extends: [storybook]
        references: [types, web, mocks]
        include: ['src/**/*.stories.{ts,tsx,mts}']

configs:
    base:
        outDir: './dist'
        target: 'module'
        module: 'esnext'
        lib: ['esnext']
        jsx: 'react'
        strict: true
    web:
        extends: [base]
        lib: ['dom', 'dom.iterable', 'esnext.asynciterable']
        jsx: 'react-jsx'
        strict: true
        types: ['react', 'react-dom', 'vite/client']
    webworker:
        extends: [web]
        lib: ['webworker']
    storybook:
        extends: [web]
        types: ['@storybook/react']
